/**
 * @fileoverview gRPC-Web generated client stub for proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: calc.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as calc_pb from './calc_pb'; // proto import: "calc.proto"


export class CalculatorClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorPlus = new grpcWeb.MethodDescriptor(
    '/proto.Calculator/Plus',
    grpcWeb.MethodType.UNARY,
    calc_pb.CalcRequest,
    calc_pb.CalcReply,
    (request: calc_pb.CalcRequest) => {
      return request.serializeBinary();
    },
    calc_pb.CalcReply.deserializeBinary
  );

  plus(
    request: calc_pb.CalcRequest,
    metadata?: grpcWeb.Metadata | null): Promise<calc_pb.CalcReply>;

  plus(
    request: calc_pb.CalcRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: calc_pb.CalcReply) => void): grpcWeb.ClientReadableStream<calc_pb.CalcReply>;

  plus(
    request: calc_pb.CalcRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: calc_pb.CalcReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.Calculator/Plus',
        request,
        metadata || {},
        this.methodDescriptorPlus,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.Calculator/Plus',
    request,
    metadata || {},
    this.methodDescriptorPlus);
  }

}

